crm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('customer/',include('customer.urls')),
    path('sales/',include('sales.urls')),
    path('',include('system.urls')),
    path('admin/', admin.site.urls),
]

sales/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name='sales'

urlpatterns=[
    path('sale_chance_index/',views.sale_chance_index,name='sale_chance_index'),
    path('select_sale_chance_list/',views.select_sale_chance_list,name='select_sale_chance_list')

]

system/urls.py
# -*- coding:utf-8 -*-
from django.urls import  path
from . import views

#命名空间
app_name='system'

urlpatterns=[

    #用户返回注册登录的html页面的控制函数
    path('login_register/',views.login_register,name='login_register'),
    #ajax处理是否数据库里用户名唯一
    path('system/unique_username/',views.unique_username,name='unique_username'),
    #ajax处理是否邮箱唯一可以使用
    path('system/unique_email/',views.unique_email,name='unique_email'),
    #发送邮箱验证码方法
    path('system/send_email/',views.send_email,name='send_email'),
    #处理来自激活码邮件的get请求,并返回给页面信息
    path('system/active_accounts/',views.active_accounts,name='active_accounts'),
    #处理登录
    path('system/login_user/',views.login_user,name='login_user'),
    path('index/',views.index,name='index'),
    path('system/update_password/',views.update_password,name=' update_password'),
    path('system/logout/',views.logout,name='logout')

]

system/models.py
from django.db import models
from datetime import datetime


# 模型管理器
class ModelManager(models.Manager):

    def get_queryset(self):
        return super(ModelManager, self).get_queryset().filter(is_valid=1)


# 用户模型
class User(models.Model):
    username = models.CharField(max_length=20, db_column='user_name')
    password = models.CharField(max_length=100)
    truename = models.CharField(max_length=20, null=True, db_column='true_name')
    email = models.CharField(max_length=30)
    phone = models.CharField(max_length=20, null=True)
    is_valid = models.IntegerField(max_length=4, default=1)
    create_date = models.DateTimeField(default=datetime.now())
    update_date = models.DateTimeField(null=True)
    code = models.CharField(max_length=255, null=True)
    status = models.BooleanField(max_length=1, default=0)
    timestamp = models.CharField(max_length=255, null=True)

    objects = ModelManager()

    # 元信息
    class Meta(object):
        db_table = 't_user'

system/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.http import require_POST,require_GET
from .models import User
from django.http import  JsonResponse
from email.header import   Header# 如果包含中文，需要通过Header对象进行编码
from email.mime.text import  MIMEText
from email.utils import  parseaddr,formataddr
import smtplib
import  uuid
from datetime import  datetime,timedelta
from hashlib import  md5
import base64

# Create your views here.

#跳转到登录和注册页面
def login_register(request):
    return render(request, 'system/login_register.html')


# 验证用户名是否唯一,并返回响应状态码对应的提示信息给前台
@require_POST
def unique_username(request):
    try:
    # 接收参数
        username=request.POST.get('username')
    # 查询是否有该用户，如果不存在，可能汇报异常，也可参考get_or_方法？
        user=User.objects.get(username=username)
        user_name=user.username
    # 有用户返回页面json
        context={'code': 400, 'msg': '用户名已存在','user_name':username}
        return JsonResponse(context)
    except User.DoesNotExist as e:
        # 异常信息说明用户不存在
        return JsonResponse({'code': 200, 'msg': '用户名可以使用'})

@require_POST
def unique_email(request):
    try:
        # 接收参数
        email=request.POST.get('email')

        #查询是否有该用户
        user=User.objects.get(email=email)
        user_email=user.email
        # 有用户返回页面json
        return JsonResponse({'code':400, 'msg':'邮箱已经存在','user_email':user_email})
    except User.DoesNotExist as e:
        return JsonResponse({'code':200,'msg':'可以使用该邮箱'})


# -----------------email模块构建邮件发送实体对象--------------
# 格式化邮箱(不格式化会被当做垃圾邮件去发送或者发送失败)
def format_addr(s):
    name, addr = parseaddr(s)  # 比如：尚学堂 <java_mail01@163.com>
    # 因为name可能会有中文，需要对中文进行编码
    return formataddr((Header(name, 'utf-8').encode('utf-8'), addr))

# 邮件发送
@require_POST
def send_email(request):
    try:
     # --------------------------准备数据-------------start-------------
        # 发送邮箱
        from_addr='jjjkauau@126.com'
        # 程序代码中登录的密码其实就是那个你设置的授权码
        password='jjjkauau126'
        # 发送服务器
        smtp_server="smtp.126.com"
        # 接收邮箱
        to_addr=request.POST.get('email')

        #邮箱截取


        #用户名
        username=request.POST.get('username')
        #密码
        u_pwd=request.POST.get('password')
        #使用md5加密
        u_pwd = md5(u_pwd.encode(encoding='utf-8')).hexdigest()
        print(u_pwd,type(u_pwd))
        #激活码
        code=''.join(str(uuid.uuid4()).split('-'))
        # 10分钟后的时间戳
        td=timedelta(minutes=10)
        ts=datetime.now()+td
        # print(ts,type(ts))
     #<class 'datetime.datetime'>
        ts=str(ts.timestamp()).split('.')[0]

     # --------------------------准备数据---------------end-----------

     # -----------------------插入数据库数据----------start--------------
        user = User(username=username, password=u_pwd, email=to_addr, code=code, timestamp=ts)
        user.save()
        # -----------------------插入数据库数据----------end--------------

        # ------------------------构建邮件内容对象----------start--------------
        html = """
                          <html>
                              <body>
                                  <div>
                                  Email 地址验证<br>
                                  这封信是由 上海尚学堂 发送的。<br>
                                  您收到这封邮件，是由于在 上海尚学堂CRM系统 进行了新用户注册，或用户修改 Email 使用了这个邮箱地址。<br>
                                  如果您并没有访问过 上海尚学堂CRM，或没有进行上述操作，请忽略这封邮件。您不需要退订或进行其他进一步的操作。<br>
                                  ----------------------------------------------------------------------<br>
                                   帐号激活说明<br>
                                  ----------------------------------------------------------------------<br>
                                  如果您是 上海尚学堂CRM 的新用户，或在修改您的注册 Email 时使用了本地址，我们需要对您的地址有效性进行验证以避免垃圾邮件或地址被滥用。<br>
                                  您只需点击下面的链接激活帐号即可：<br>
                                  <a href="http://www.justin.com/system/active_accounts/?username={}&code={}&timestamp={}">http://www.justin.com/system/active_accounts/?username={}&amp;code={}&amp;timestamp={}</a><br/>
                                  感谢您的访问，祝您生活愉快！<br>
                                  此致<br>
                                   上海尚学堂 管理团队.
                                  </div>
                              </body>
                          </html>
                       """.format(username, code, ts, username, code, ts)
        msg = MIMEText(html, "html", "utf-8")

        # 标准邮件需要三个头部信息： From To 和 Subject
        # 设置发件人和收件人的信息 u/U:表示unicode字符串
        # 比如：尚学堂 <java_mail01@163.com>
        msg['From'] = format_addr(u'尚学堂<%s>' % from_addr)  # 发件人
        to_name = username  # 收件人名称
        msg['To'] = format_addr(u'{}<%s>'.format(to_name) % to_addr)  # 收件人

        # 设置标题
        # 如果接收端的邮件列表需要显示发送者姓名和发送地址就需要设置Header，同时中文需要encode转码
        msg['Subject'] = Header(u'CRM系统官网帐号激活邮件', 'utf-8').encode()
        # ------------------------构建邮件内容对象-----------end-------------

        # ------------------------------发送--------------start----------------
        # 创建发送邮件服务器的对象
        server = smtplib.SMTP(smtp_server, 25)
        # 设置debug级别0就不打印发送日志，1打印
        server.set_debuglevel(1)
        # 登录发件邮箱
        server.login(from_addr, password)
        # 调用发送方法 第一个参数是发送者邮箱，第二个是接收邮箱，第三个是发送内容
        server.sendmail(from_addr, [to_addr], msg.as_string())
        # 关闭发送
        server.quit()
        # ------------------------------发送----------------end--------------

        # 返回页面提示信息
        return JsonResponse({'code': 201, 'msg': '注册成功，请前往邮箱激活帐号'})

    except smtplib.SMTPException as e:
    # 返回页面提示信息
        return JsonResponse({'code': 400, 'msg': '注册失败，请重新注册！'})

 #其中get内含有键值对的参数包括username,激活码  ，过期的时间戳字符串
@require_GET
def active_accounts(reqeuest):
    try:
        #用户名
        username=reqeuest.GET.get('username')
        #激活码
        code=reqeuest.GET.get('code')
        #过期时间
        ts=reqeuest.GET.get('timestamp')
        #根据用户和激活码查询是否有该账号
        user=User.objects.get(username=username,code=code,timestamp=ts)
        # 根据过期时间判断帐号是否有效
        now_ts = str(datetime.now().timestamp()).split('.')[0]
        if int(now_ts)>int(ts):
            # 链接失效，返回提示信息，删除数据库信息
            user.delete()
            return HttpResponse('<h1>该链接已经失效，请重新注册&nbsp;&nbsp;<a href="http://www.justin.com/login_register/"上海丽特CRM系统</a></h1>')
        #没有过期，激活账号，清除激活码，改变状态
        user.code='' #清除激活码
        user.status=1 #有效账号
        user.save()
        # 返回提示信息
        return HttpResponse(
            '<h1>账号激活成功，请到网系统登录&nbasp;&nbsp;<a href="http://www.justin.com/login_register/">上海丽特CRM系统</a></h1>'

        )
    except Exception as e:
        if isinstance(e,User.DoesNotExist):
            return HttpResponse('<h1>该链接已经失效，请重新注册&nbsp;&nbsp;<a href="http://www.justin.com/login_register/">上海丽特CRM系统</a></h1>')
        return HttpResponse('<h1>不好意思，网络出现了波动，激活失败，请重新尝试</h1>')


# 登录

@require_POST

def login_user(request):
    try:
        #接收前台传来的数据
        # 账号
        username=request.POST.get('username')
        #密码
        password=request.POST.get('password')
        #记住密码

        remeber=request.POST.get('remember')
        print(remeber,type(remeber))

        #5天免登录
        login_free = request.POST.get('login_free')

        forgot_pwd=request.POST.get('forgot_pwd')

        # 使用md5加密
        password_md5=md5(password.encode(encoding='utf-8')).hexdigest()

        #查询
        user=User.objects.get(username=username,password=password_md5)

        # 如果用户存在，存储sesison信息

        request.session['u_s_n']=username

        #如果选选择存储5天的sesison，没选择浏览器关闭session失效
        if  login_free:
            ex=(datetime.now()+timedelta(days=6)).timestamp()
            request.session.set_expiry(ex)
        else:
            request.session.set_expiry(0)




        # 返回成功提示信息
        context={'code':200,'msg':'欢迎回来'}

        # 实现记住密码
        # 如果用户存在，前台js存储cookie
        # 存储格式：key -> login_cookie, value -> username&password
        # 由于功能改造，代码重构
        if 'true' == remeber:
           # context['login_cookie'] = base64.b64encode((username + '&' + password).encode(encoding='utf-8')).decode(encoding='utf-8')
           context['login_user_cookie'] = base64.b64encode(username.encode(encoding='utf-8')).decode(encoding='utf-8')
           context['login_pwd_cookie'] = base64.b64encode(password.encode(encoding='utf-8')).decode(encoding='utf-8')

        # #实现忘记密码功能
        # if format_addr:
        #     return render(request,'forgot.html.html')

        return JsonResponse(context)


    except User.DoesNotExist as e:
        context={'code':400,'msg':'用户名或密码错误'}
        return JsonResponse(context)



def index(request):
        # 判断session中是否有用户信息
        username=request.session.get('u_s_n')

        if username:
            return render(request, 'system/index1.html')
        # 如果不存在，重定向登录页面
        return redirect('system:login_register',permanent=True)




#修改密码
@require_POST
def update_password(request):
    try:
        username=request.POST.get('username')
        old_password=request.POST.get('old_password')
        new_password=request.POST.get('new_password')

        #使用md5加密
        old_password_md5=md5(old_password.encode(encoding='utf-8')).hexdigest()

        # 查询用户密码是否正确
        user=User.objects.get(username=username,password=old_password)

        #使用md5加密
        new_password_md5=md5(new_password.encode(encoding='utf-8')).hexdigest()


        #修改密码
        user.password=new_password_md5
        user.save()

        # 修改密码要重新登录，所以要安全退出
        # 安全退出系统要清除session，所以这里不写
        return JsonResponse({'code':200,'msg':'修改成功'})
    except User.DoesNotExist as e:
        return  JsonResponse({'code':400,'msg':'原密码输入错误'})

    #安全退出

def logout(request):
        try:
            #清除session
            request.session.flush()

            #重定向到登录页面
            return  redirect('system:login_register')
        except Exception as e:
            #重定向至登录页面
            return  redirect('system:login_register')

templates/system/forgot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>忘记密码</title>
</head>
<body>
<form id="forgot_form" style="postion:absoulute;top:40%;left: 40%;border: 1px solid aqua;padding: 10px"
action="#">
     {% csrf_token %}
        <span style="color: red"></span>
        <p><label>用户名:<input name="username" /></label></p>
        <p><label>密&nbsp;&nbsp;&nbsp;码: <input name="password"></label></p>
        <input  style="float: right;width: 100px" id="register_btn" type="submit" value="注&nbsp;&nbsp;&nbsp;册">


</form>

</body>
</html>

templates/system/index1.html
<!DOCTYPE html>
{# 导入静态资源 #}
{% load static %}
<html>
<head>
    <title>客户关系管理系统</title>
  {% include 'base.html' %}
</head>
<body class="easyui-layout">
{# 上边 #}
<div region="north" style="height: 78px;background-color: #E0ECFF;overflow: hidden;">
    <table style="padding: 5px" width="100%">
        <tr>
            <td width="50%">
                <img alt="logo" src="{% static '/images/bglogo.png' %}">
            </td>
            <td valign="bottom" align="right" width="50%">
                <strong style="font-size: 16px">欢迎【{{ request.session.u_s_n }}】登录</strong>
            </td>
        </tr>
    </table>
</div>
{# 中间 #}
<div region="center">
    <div class="easyui-tabs" fit="true" border="false" id="tabs">
        <div title="首页" data-options="iconCls:'icon-home'">
            <div align="center" style="padding-top: 100px"><font color="red" size="10">欢迎回来</font></div>
        </div>
    </div>
</div>
{# 左边菜单 #}
<div region="west" style="width: 200px" title="导航菜单" split="true">
    <div class="easyui-accordion" data-options="fit:true,border:false">

        <div title="营销管理" data-options="selected:true,iconCls:'icon-yxgl'" style="padding: 10px">
            <a href="javascript:openTab('营销机会管理','{% url 'sales:sale_chance_index' %}','icon-yxjhgl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-yxjhgl'" style="width: 150px">营销机会管理</a>
            <a href="javascript:openTab('客户开发计划','','icon-khkfjh')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khkfjh'" style="width: 150px">客户开发计划</a>
        </div>

        <div title="客户管理" data-options="iconCls:'icon-khgl'" style="padding:10px;">
            <a href="javascript:openTab('客户信息管理','','icon-khxxgl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khxxgl'" style="width: 150px;">客户信息管理</a>
            <a href="javascript:openTab('客户流失管理','','icon-khlsgl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khlsgl'" style="width: 150px;">客户流失管理</a>
        </div>


        <div title="服务管理" data-options="iconCls:'icon-fwgl'" style="padding:10px">
            <a href="javascript:openTab('服务创建','','icon-fwcj')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwcj'" style="width: 150px;">服务创建</a>
            <a href="javascript:openTab('服务分配','','icon-fwfp')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwfp'" style="width: 150px;">服务分配</a>
            <a href="javascript:openTab('服务处理','','icon-fwcl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwcl'" style="width: 150px;">服务处理</a>
            <a href="javascript:openTab('服务反馈','','icon-fwfk')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwfk'" style="width: 150px;">服务反馈</a>
            <a href="javascript:openTab('服务归档','','icon-fwgd')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwgd'" style="width: 150px;">服务归档</a>
        </div>


        <div title="统计报表" data-options="iconCls:'icon-tjbb'" style="padding:10px">
            <a href="javascript:openTab('客户贡献分析','','icon-khgxfx')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khgxfx'" style="width: 150px;">客户贡献分析</a>
            <a href="javascript:openTab('客户构成分析','','icon-khgcfx')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khgcfx'" style="width: 150px;">客户构成分析</a>
            <a href="javascript:openTab('客户服务分析','','icon-khfwfx')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khfwfx'" style="width: 150px;">客户服务分析</a>
            <a href="javascript:openTab('客户流失分析','','icon-khlsfx')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khlsfx'" style="width: 150px;">客户流失分析</a>
        </div>


        <div title="基础数据管理" data-options="iconCls:'icon-jcsjgl'" style="padding:10px">
            <a href="javascript:openTab('数据字典管理','','icon-sjzdgl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-sjzdgl'" style="width: 150px;">数据字典管理</a>
            <a href="javascript:openTab('产品信息查询','','icon-cpxxgl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-cpxxgl'" style="width: 150px;">产品信息查询</a>
        </div>


        <div title="系统管理" data-options="iconCls:'icon-item'" style="padding:10px">
            <a href="javascript:openTab('用户管理','','icon-user')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-user'" style="width: 150px;">用户管理</a>
            <a href="javascript:openTab('角色管理','','icon-user')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-user'" style="width: 150px;">角色管理</a>
            <a href="javascript:openTab('模块管理','','icon-user')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-user'" style="width: 150px;">模块管理</a>
            <a href="javascript:open_update_password_dialog('{{ request.session.u_s_n }}');" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-modifyPassword'" style="width: 150px;">修改密码</a>
            <a href="javascript:logot();" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-exit'"
               style="width: 150px;">安全退出</a>
        </div>

    </div>
</div>
{# 下边菜单 #}
<div region="south" style="height: 25px;padding: 5px;overflow: hidden;" align="center">
    版本所有 上海尚学堂 <a href="http://www.shsxt.com" target="_blank">www.shsxt.com</a>(2016-2026)
</div>

{# 修改密码对话框 #}
<div id="system_index_update_password_dialog" class="easyui-dialog">
    <form id="system_index_update_password_form" method="post">
        <input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken"/>
        <table>
            <tr>
                <td>用户名：</td>
                <td>
                    <input id="username" name="username" readonly value="{{ request.session.u_s_n }}"/>
                </td>
            </tr>
            <tr>
                <td>原密码：</td>
                <td><input type="password" name="old_password" class="easyui-validatebox"
                           data-options="required:true,missingMessage:'原密码不可以为空',validType:['check_pwd_length', 'regex_check_pwd']"/></td>
            </tr>
            <tr>
                <td>新密码：</td>
                <td><input type="password" name="new_password" id="new_password" class="easyui-validatebox" data-options="required:true,missingMessage:'新密码不可以为空',validType:['check_pwd_length', 'regex_check_pwd']"/></td>
            </tr>
            <tr>
                <td>确认密码：</td>
                <td><input type="password" class="easyui-validatebox"
                           data-options="required:true,missingMessage:'确认密码不可以为空',validType:['check_pwd_length', 'regex_check_pwd', 'eq_pwd[\'#new_password\']']"/></td>
            </tr>
        </table>
    </form>
</div>
</body>
<script type="text/javascript" src="{% static '/js/reg_utils.js' %}"></script>
<script type="text/javascript" src="{% static '/js/system/index.js' %}"></script>
</html>

</body>
</html>

templates/system/login_register.html
<!DOCTYPE html>
{# 导入静态资源 #}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>登录</title>
      {# 导入网站icon图标,  可以在线生成 #}

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- 导入base页面 -->
    {% include 'base.html' %}

    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet"/>
<link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet"/>
<link href="{% static 'assets/css/main.css' %}" rel="stylesheet"/>

</head>
<body class="login-page">
{# csrf保护 #}
{% csrf_token %}
<!-- Start #login -->
<div id="login" class="animated bounceIn">
    <div class="login-wrapper">
        <ul id="myTab" class="nav nav-tabs nav-justified bn">
            <li>

                <a data-toggle="tab" id="login_top" style="cursor: pointer">登录</a>
            </li>
            <li class="">
                <a data-toggle="tab" id="reg_top" style="cursor: pointer">注册</a>
            </li>
        </ul>

        <!--登录板块-->
        <div id="myTabContent" class="tab-content bn">
            <div class="tab-pane fade active in" id="log-in">
                <form class="form-horizontal mt10" action="index.html" id="login-form" role="form">
                         <b><span id="login_span"></span></b>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <input type="text" name="username" id="login_username" class="form-control left-icon"
                                   placeholder="请输入用户名 (字母开头，字母加数字)">
                            <i class="ec-user s16 left-input-icon"></i>
                        </div>
                    </div>
                    <div class="form-group" style="display: none">
                        <div class="col-lg-12">
                            <input type="text" name="email" id="email" class="form-control left-icon"
                                   placeholder="请输入邮箱">
                            <i class="ec-user s16 left-input-icon"></i>
                        </div>
                    </div>

                    <!--密码输入框-->

                    <div class="form-group">
                        <div class="col-lg-12">
                            <input type="password" name="password" id="login_password" autocomplete="new-password"
                                   class="form-control left-icon"
                                   placeholder="请输入密码">
                            <i class="ec-locked s16 left-input-icon"></i>
                        </div>
                    </div>

                          <!--忘记密码-->
                       <div class="form-group">
                        <div class="col-lg-12">
                            <span  class="help-block"><a id='forgot_pwd'><small>忘记密码 ?</small></a></span>
                        </div>
                    </div>


                    <!--记住密码-->

                    <div class="form-group">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8">
                            <!-- col-lg-12 start here -->
                            <label class="checkbox">
                                <input type="checkbox" name="remember" id="remember" value="option">记住密码 ?
                            </label>
                        </div>

                        <div class="form-group">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8">
                            <!-- col-lg-12 start here -->
                            <label class="checkbox">
                                <input  id='login_free'type="checkbox" name="login_free" id="remember" value="option">5天免登录 ?
                            </label>
                        </div>

                        <!-- col-lg-12 end here -->
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-4">
                            <!-- col-lg-12 start here -->
                            <button   id="login_btn" class="btn btn-success pull-right" type="button">登录</button>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                         </div>
                </form>
            </div>

            <!--register输入框-->

            <div class="tab-pane fade active in" id="register" style="display: none;">
                <form class="form-horizontal mt20" action="#" id="register-form" role="form">
                    <!-- 在注册的div上展示相应提示信息-->
                    <b><span id="reg_span"></span></b>

                    <!-- 注册输入用户-->
                    <div class="form-group">
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <input id="reg_uname" name="reg_uname" type="email" class="form-control left-icon"
                                   placeholder="请输入用户名(字母开头,字母数字组合)">
                            <i class="ec-mail s16 left-input-icon"></i>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>

                    <!-- 注册输入邮箱-->
                    <div class="form-group">
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <input id="reg_email" name="reg_email" type="email" class="form-control left-icon"
                                   placeholder="请输入邮箱">
                            <i class="ec-mail s16 left-input-icon"></i>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- 注册输入密码-->
                    <div class="form-group">
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <input type="password" class="form-control left-icon" id="reg_pwd" name="password"
                                   autocomplete="new-password" placeholder="请输入密码(必须数字字母大小写特殊符号)">
                            <i class="ec-locked s16 left-input-icon"></i>
                        </div>
                        <!-- 注册确认密码-->
                        <!-- col-lg-12 end here -->
                        <div class="col-lg-12 mt15">
                            <!-- col-lg-12 start here -->
                            <input type="password" class="form-control left-icon" id="confirm_password"
                                   name="repeat_passowrd" autocomplete="new-password" placeholder="请再次输入密码">
                            <i class="ec-locked s16 left-input-icon"></i>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- 注册提交按钮-->
                    <div class="form-group">
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <input type="button" class="btn btn-success btn-block" id="reg_btn" value="单击注册"/>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- End #.login-wrapper -->
</div>


<!-- 导入jquery文件 -->

<script type="text/javascript" src="{% static 'js/system/login_register.js' %}"></script>
</body>
</html>