crm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('customer/',include('customer.urls')),
    path('sales/',include('sales.urls')),
    path('',include('system.urls')),
    path('admin/', admin.site.urls),
]

sales/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name='sales'

urlpatterns=[
    path('sale_chance_index/',views.sale_chance_index,name='sale_chance_index'),
    path('select_sale_chance_list/',views.select_sale_chance_list,name='select_sale_chance_list')

]

sales/models.py
from django.db import models

class ModelManager(models.Manager):
    def get_queryset(self):
        return  super(ModelManager,self).get_queryset().filter(isValid=1)


# 营销机会模型
class SaleChance(models.Model):
    # 信息来源
    chanceSource = models.CharField(max_length=300, db_column='chance_source')
    # 客户id
    customerId = models.IntegerField(db_column='customer_id')
    # 客户名称
    customerName = models.CharField(max_length=100, db_column='customer_name')
    # 成功几率
    cgjl = models.IntegerField(db_column='cgjl')
    # 概要
    overview = models.CharField(max_length=300, db_column='overview')
    # 联系人
    linkMan = models.CharField(max_length=20, db_column='link_man')
    # 联系电话
    linkPhone = models.CharField(max_length=20, db_column='link_phone')
    # 描述
    description = models.CharField(max_length=1000, db_column='description')
    # 创建人
    createMan = models.CharField(max_length=20, db_column='create_man')
    # 分配给谁
    assignMan = models.CharField(max_length=20, db_column='assign_man')
    # 分配时间
    assignTime = models.DateTimeField(db_column='assign_time')
    # 状态：1-如果有分配就是已分配状态，0-未分配
    state = models.CharField(max_length=20, db_column='state')
    # 开发状态：0=未开发 1=开发中 2=开完完成 3=开发失败
    devResult = models.CharField(max_length=20, db_column='dev_result')

    isValid = models.IntegerField(db_column='is_valid', default=1)
    createDate = models.DateTimeField(db_column='create_date', auto_now_add=True)
    updateDate = models.DateTimeField(max_length=20, db_column='update_date')

    objects = ModelManager()

    class Meta:
        db_table = 't_sale_chance'


# 客户计划model
class CusDevPlan(models.Model):
    # 关联营销机会
    saleChance = models.ForeignKey(SaleChance, db_constraint=False,
                                   db_column='sale_chance_id', on_delete=models.DO_NOTHING)
    # 计划内容
    planItem = models.CharField(max_length=300, db_column='plan_item')
    # 计划时间
    planDate = models.DateTimeField(max_length=20, db_column='plan_date')
    # 执行效果
    exeAffect = models.CharField(max_length=100, db_column='exe_affect')
    isValid = models.IntegerField(db_column='is_valid')
    createDate = models.DateTimeField(db_column='create_date')
    updateDate = models.DateTimeField(max_length=20, db_column='update_date')

    objects = ModelManager()

    class Meta:
        db_table = 't_cus_dev_plan'

sales/views.py
from django.shortcuts import render
import pymysql
from dbutils import  pymysql_pool
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.core.paginator import  Paginator
from django.views.decorators.csrf import  csrf_exempt
from sales.models import SaleChance
from datetime import  datetime



# 准备数据
config = {
    'host': 'localhost',  # 数据库ip
    'port': 3306,  # 数据库用户名
    'user': 'root',  # 数据库密码
    'password': '123456',  # 数据库端口
    'database': 'crm',  # 具体的一个库 等价于database
    'charset': 'utf8mb4',  # 字符集
    # 默认获取的数据是元祖类型，如果想要或者字典类型的数据
    'cursorclass': pymysql.cursors.DictCursor
}

#初始化连接池对象
connect_pool=pymysql_pool.ConnectionPool(size=50,name='mysql_pool',**config)


#从数据库连接池中获取连接
def connect():
    #从连接池中获取连接
    connection=connect_pool.get_connection()
    return  connection


def sale_chance_index(request):
    '''跳转营销机会首页'''
    return  render(request,'sales/sale_chance.html')

@csrf_exempt
@require_POST
def select_sale_chance_list(request):
    '''查询所有营销机会'''
    try:
        #获取第几页
        page_num=request.POST.get('page')

        #获取每页多少条
        page_size=request.POST.get('rows')

        #获取连接
        connection=connect()

        #创建游标对象
        cursor=connection.cursor()

        #编写sql
        sql='''
               SELECT
                    sc.id id,
                    c.id customerId, 
                    c.khno khno,
                    c.name customerName,
                    sc.overview overview,
                    sc.create_man createMan,
                    cl.id linkManId,
                    cl.link_name linkManName,
                    cl.phone linkPhone,
                    u.user_name assignMan,
                    sc.assign_time assignTime,
                    sc.state state,
                    sc.dev_result devResult
                    FROM
                        t_sale_chance sc
                LEFT JOIN t_customer c ON sc.customer_id = c.id
                LEFT JOIN t_user u ON u.id = sc.assign_man
                LEFT JOIN t_customer_linkman cl ON cl.id = sc.link_man
                WHERE 1 = 1        
            '''

        #如果用户选择了其他条件，拼接sql
        #客户名称
        customerName=request.POST.get('cn')
        #概要
        overview=request.POST.get('ow')
        # 创建人
        creatman=request.POST.get('cm')
        # 分配状态
        state = request.POST.get('st')

        if customerName:
            sql+='  AND c.name like "%{}%"  '.format(customerName)

        if overview:
            sql+='  AND sc.overview like "%{}%"  '.format(overview)

        if creatman:
            sql+='  AND sc.create_man like "%{}%"  '.format(creatman)

        if state:
            sql+=' AND sc.state = {}   '.format(state)


        sql+='  ORDER BY sc.id DESC; '

        #执行sql
        cursor.execute(sql)

        #返回多条结果行
        object_lists=cursor.fetchall()  #查询当前sql执行后所有记录

        #关闭游标
        cursor.close()

        #初始化分页对象
        p=Paginator(object_lists,page_size)

        #获取指定页数的数据
        data=p.page(page_num).object_list

        #返回总条数
        count=p.count

        #返回数据
        context={
            'total':count,
            'rows':data
        }

        return JsonResponse(context)

    except Exception as e:
        print(e)
        return JsonResponse({'code':400,'msg':'error'})

    finally:
        #关闭游标连接
        connection.close()

templates/sales/sale_chance.html
<!DOCTYPE html>
{% load static %}
<html >
<head>
    <meta charset="UTF-8">
    <title>营销机会管理</title>
       <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    {% include 'base.html' %}

</head>
<body>

<div style="margin:5px 0;"></div>
<table id="dg" class="easyui-datagrid" title="营销机会管理"
       data-options="rownumbers:true,singleSelect:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'sales:select_sale_chance_list' %}',method:'post'">

    <thead>
     <tr>
        <th data-options="field:'khno',width:90">客户编号</th>
        <th data-options="field:'customerName',width:184">客户名称</th>
        <th data-options="field:'overview',width:180">概要</th>
        <th data-options="field:'createMan',width:90">创建人</th>
        <th data-options="field:'linkManName',width:90">联系人</th>
        <th data-options="field:'linkPhone',width:100">联系电话</th>
        <th data-options="field:'assignMan',width:90">分配给谁</th>
        <th data-options="field:'assignTime',width:130,">分配时间</th>
        <th data-options="field:'state',width:80,">状态</th>
        <th data-options="field:'devResult',width:80,">开发状态</th>
    </tr>
    </thead>

</table>


{# 工具栏 #}
<div id="tb">
    <a  class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true">添加</a>
    <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true">修改</a>
    <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true">删除</a>
    <div>
        客户名称&nbsp;&nbsp;<input id="customerName" onkeydown="if(event.keyCode==13)select_params_sale_chance();"/>
        &nbsp;&nbsp;概要&nbsp;&nbsp;<input id="overview" onkeydown="if (event.keyCode==13) select_params_sale_chance();"/>
        &nbsp;&nbsp;创建人&nbsp;&nbsp;<input id="createMan"onkeydown="if (event.keyCode==13) select_params_sale_chance();"/>
        &nbsp;&nbsp;分配状态&nbsp;&nbsp;
        <select class="easyui-combobox" id="state" style="width: 100px">
            <option value="">全部</option>
            <option value="0">未分配</option>
            <option value="1">已分配</option>
        </select>&nbsp;&nbsp;
        <a id="btn" onclick=" select_params_sale_chance();" class="easyui-linkbutton"
           data-options="iconCls:'icon-search'">查询</a>
    </div>
</div>


{# 添加营销机会对话框 #}
<div id="sales_sale_chance_create_dialog" class="easyui-dialog">
    <form id="sales_sale_chance_form" method="post">
        <input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken"/>
        <table cellpadding="10px">
            <tr>
                <td style="padding-right: 10px">客户名称</td>
                <td>
                    <input type="text" id="customerName_hidden" name="customerName_hidden">
                    <select  id="customer_select" name="customerId" style="width: 173px"></select>
                    <span style="color: red;padding-left: 10px">*</span>
                </td>
                <td style="padding-left: 70px;padding-right: 10px">机会来源</td>
                <td><input name="chanceSource"/></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">联系人</td>
                <td>
                    <input type="hidden" id="linkManName_hidden" name="linkManName">
                    <select  name="linkMan" id="linkman_select" style="width: 173px"></select>
                </td>
                <td style="padding-left: 70px;padding-right: 10px">联系电话</td>
                <td>
                    <input readonly id="linkPhone" name="linkPhone"/>
                </td>
            </tr>
            <tr>
                <td style="padding-right: 10px">成功几率(%)</td>
                <td colspan="3"><input name="cgjl"/><span style="color: red;padding-left: 10px">*</span></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">概要</td>
                <td colspan="3"><input name="overview" style="width: 500px"/></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">机会描述</td>
                <td colspan="3"><textarea name="description" style="width: 498px;height: 100px"></textarea></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">指派给</td>
                <td colspan="3">
                    <select name="username" id="username_select" style="width: 173px"></select>
                </td>
            </tr>
        </table>
    </form>
</div>

</body>
    <script type="text/javascript" src="{% static '/js/sales/sale_chance.js' %}"></script>
</html>